# Generated by Django 4.1.3 on 2022-11-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_post_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nim', models.CharField(max_length=9)),
                ('Foto', models.ImageField(upload_to='')),
                ('Nama', models.TextField(max_length=20)),
                ('Kelas', models.TextField(max_length=10)),
                ('Semester', models.TextField(max_length=10)),
                ('Telepon', models.IntegerField()),
                ('Alamat', models.TextField(max_length=20)),
                ('Jenis_Kelamin', models.TextField(max_length=10)),
            ],
        ),
    ]
