# Generated by Django 4.1.3 on 2022-11-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAbsen', models.TextField(max_length=50)),
                ('keterangan', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='beritaAcara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAcara', models.TextField(max_length=50)),
                ('pertemuan', models.TextField(max_length=5)),
                ('tanggal', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.TextField(max_length=15)),
                ('namaDosen', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFoto', models.IntegerField()),
                ('namaFoto', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='golongan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGol', models.TextField(max_length=2)),
                ('namaGol', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idJadwal', models.TextField(max_length=50)),
                ('ruangan', models.TextField(max_length=5)),
                ('hari', models.TextField(max_length=30)),
                ('jamMulai', models.IntegerField()),
                ('jamSelesai', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='mataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeMK', models.TextField(max_length=10)),
                ('mataKuliah', models.TextField(max_length=50)),
                ('sks', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='Telepon',
            field=models.TextField(max_length=14),
        ),
    ]
